<?php

/**
 * Implementation of hook_uninstall().
 */
function uc_rbkmoney_uninstall() {
  // Delete variables
  variable_del('uc_rbkmoney_actionURL');
  variable_del('uc_rbkmoney_eshopId');
  variable_del('uc_rbkmoney_recipientCurrency');
  variable_del('uc_rbkmoney_secretKey');
  variable_del('uc_rbkmoney_log');
  variable_del('uc_rbkmoney_ip');
  variable_del('uc_rbkmoney_preference');
}