<?php

/**
 * @file
 * Integrates RBK Money's payment service.
 */
/**
 * Define payment statuses
 */
define('STATUS_PROCESS', 3);
define('STATUS_SUCCESS', 5);
define('UC_RBKMONEY_ALLOWED_IP', '89.111.188.128, 46.38.182.208, 46.38.182.209, 46.38.182.210');

/**
 * Implements hook_perm().
 */
function uc_rbkmoney_perm() {
  return array('administer uc_rbkmoney');
}

/**
 * Implements hook_menu().
 */
function uc_rbkmoney_menu() {
  $items['admin/store/settings/uc_rbkmoney'] = array(
    'title' => 'RBK Money',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_rbkmoney_setup'),
    'access arguments' => array('administer uc_rbkmoney'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['uc_rbkmoney/response'] = array(
    'title' => 'Internal Data',
    'page callback' => 'uc_rbkmoney_done_payment',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['uc_rbkmoney/success'] = array(
    'title' => 'Internal Data',
    'page callback' => 'uc_rbkmoney_payment_end',
    'page arguments' => array('success'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['uc_rbkmoney/fail'] = array(
    'title' => 'Internal Data',
    'page callback' => 'uc_rbkmoney_payment_end',
    'page arguments' => array('fail'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Callback for settings page.
 */
function uc_rbkmoney_setup() {
  $form['uc_rbkmoney_help'] = array(
    '#value' => t(l('RBK Money API link', 'http://www.rbkmoney.ru/manual', array('attributes' => array('target' => '_blank')))),
  );

  global $base_url;
  $form['uc_rbkmoney_responseURL'] = array(
    '#type' => 'textfield',
    '#title' => t('Response URL'),
    '#default_value' => $base_url . '/uc_rbkmoney/response',
    '#description' => t('For insertion into "Payment notification URL" field on !site settings page', array('!site' => l('RBK Money', 'http://www.rbkmoney.ru', array('attributes' => array('target' => '_blank'))))),
    '#required' => false,
  );
  $form['uc_rbkmoney_actionURL'] = array(
    '#type' => 'textfield',
    '#title' => t('Payment form action URL'),
    '#default_value' => variable_get('uc_rbkmoney_actionURL', 'https://rbkmoney.ru/acceptpurchase.aspx'),
    '#description' => t('Default: "!action"', array('!action' => url('https://rbkmoney.ru/acceptpurchase.aspx'))),
    '#required' => TRUE,
  );
  $form['uc_rbkmoney_eshopId'] = array(
    '#type' => 'textfield',
    '#title' => t('Site ID'),
    '#default_value' => variable_get('uc_rbkmoney_eshopId', ''),
    '#description' => t("Merchant ID of your site"),
    '#required' => TRUE,
  );
  $form['uc_rbkmoney_recipientCurrency'] = array(
    '#type' => 'select',
    '#title' => t('Payments currency'),
    '#options' => array('RUR' => 'RUR', 'USD' => 'USD', 'EUR' => 'EUR', 'UAH' => 'UAH'),
    '#default_value' => variable_get('uc_rbkmoney_recipientCurrency', 'RUR'),
    '#description' => t("Please, select payments currency"),
    '#required' => TRUE,
  );
  $form['uc_rbkmoney_secretKey'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret key'),
    '#default_value' => variable_get('uc_rbkmoney_secretKey', ''),
    '#description' => t('Secret key, entered on !site settings page', array('!site' => l('RBK Money', 'http://www.rbkmoney.ru', array('attributes' => array('target' => '_blank'))))),
    '#required' => TRUE,
  );
  $form['uc_rbkmoney_log'] = array(
    '#type' => 'radios',
    '#title' => t('Save RBK Money\'s server responses in !dblog', array('!dblog' => l('system log', 'admin/reports/dblog'))),
    '#options' => array('on' => t('Yes'), 'off' => t('No')),
    '#default_value' => variable_get('uc_rbkmoney_log', 'on'),
  );
  $form['uc_rbkmoney_ip'] = array(
    '#type' => 'radios',
    '#title' => t('Process notifications only from allowed IP addresses'),
    '#options' => array('on' => t('Yes'), 'off' => t('No')),
    '#default_value' => variable_get('uc_rbkmoney_ip', 'off'),
    '#description' => t('List of allowed IP addresses: ') . UC_RBKMONEY_ALLOWED_IP,
  );

  $form['advanced'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced options'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['advanced']['uc_rbkmoney_preference'] = array(
    '#type' => 'select',
    '#title' => t('Prefered payment method'),
    '#options' => array(
      'all' => t('All (default)'),
      'inner' => t('RBK Money wallet (inner)'),
      'bankcard' => t('Visa/MasterCard bank card (bankcard)'),
      'terminals' => t('Cash-in kiosks (terminals)'),
      'prepaidcard' => t('RBK Money prepaid card (prepaidcard)'),
      'postrus' => t('Russian Post (postrus)'),
      'mobilestores' => t('Mobile stores (mobilestores)'),
      'transfers' => t('Money transfer systems (transfers)'),
      'ibank' => t('Internet banking (ibank)'),
      'sberbank' => t('Bank payment (sberbank)'),
      'svyaznoy' => t('Svyaznoy salons (svyaznoy)'),
      'euroset' => t('Euroset salons (euroset)'),
      'contact' => t('Contact salons (contact)'),
      'mts' => t('MTS salons (contact)'),
      'uralsib' => t('Uralsib (uralsib)'),
      'handybank' => t('HandyBank (handybank)'),
      'ocean' => t('Ocean Bank (ocean)'),
      'ibankuralsib' => t('Uralsib internert bank (ibankuralsib)'),
    ),
    '#default_value' => variable_get('uc_rbkmoney_preference', 'all'),
    '#description' => t("Default payment method. Allow to skip payment method selection page"),
  );
  $form['advanced']['uc_rbkmoney_recurring'] = array(
    '#type' => 'select',
    '#title' => t('Reccuring payment'),
    '#options' => array('false' => 'false', 'true' => 'true'),
    '#default_value' => variable_get('uc_rbkmoney_recurring', 'false'),
    '#description' => t("Set reccuring payment mode (default: false)"),
  );
  $form['advanced']['uc_rbkmoney_version'] = array(
    '#type' => 'select',
    '#title' => t('Protocol version'),
    '#options' => array(1 => 1, 2 => 2),
    '#default_value' => variable_get('uc_rbkmoney_version', 1),
    '#description' => t("Set protocol version (default: 1)"),
  );
  $form['advanced']['uc_rbkmoney_direct'] = array(
    '#type' => 'select',
    '#title' => t('Direct mode'),
    '#options' => array('false' => 'false', 'true' => 'true'),
    '#default_value' => variable_get('uc_rbkmoney_direct', 'false'),
    '#description' => t("Set direct payment mode (default: false)"),
  );
  $form['advanced']['uc_rbkmoney_language'] = array(
    '#type' => 'select',
    '#title' => t('Interface language'),
    '#options' => array('ru' => 'ru', 'en' => 'en'),
    '#default_value' => variable_get('uc_rbkmoney_language', 'ru'),
    '#description' => t("Please, select interface language (default: ru)"),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_payment_method().
 */
function uc_rbkmoney_payment_method() {
  $path = drupal_get_path('module', 'uc_rbkmoney') . '/images/logo.gif';
  $img = theme('image', $path, 'RBK Money', 'RBK Money', array('class' => 'system_logo'));
  $title = t('RBK Money') . '<br />' . $img;
  $methods[] = array(
    'id' => 'rbkmoney',
    'name' => t('RBK Money'),
    'title' => $title,
    'desc' => t('RBK Money'),
    'weight' => 1,
    'callback' => 'uc_payment_method_rbkmoney',
    'checkout' => TRUE,
    'no_gateway' => TRUE,
  );
  return $methods;
}

/**
 * Callback for rbkmoney payment method settings.
 */
function uc_payment_method_rbkmoney($op, &$arg1) {
  switch ($op) {
    case 'cart-details':
      return;
    case 'settings':
      return;
  }
}

/**
 * Implements hook_form_alter().
 */
function uc_rbkmoney_form_alter(&$form, $form_state, $form_id) {
  $order_id = isset($_SESSION['cart_order']) ? intval($_SESSION['cart_order']) : 0;
  if ($form_id == 'uc_cart_checkout_review_form' && $order_id > 0) {
    $order = uc_order_load($order_id);
    if ($order->payment_method == 'rbkmoney') {
      unset($form['submit']);
      $form['#prefix'] = '<table><tr><td>';
      $form['#suffix'] = '</td><td>' . drupal_get_form('uc_rbkmoney_submit_form', $order) . '</td></tr></table>';
    }
  }
}

/**
 * Payment request form.
 */
function uc_rbkmoney_submit_form($form_state, $order) {
  $desc = '';
  foreach ($order->products as $value) {
    if (!empty($desc)) {
      $desc .= ', ';
    }
    $desc .= $value->qty . '&times; ' . check_plain($value->title);
  }
  if (drupal_strlen($desc) > 255) { // Prevent more than 255 symbols of order description.
    $desc = t('Order number !num', array('!num' => $order->order_id));
  }

  $form['eshopId'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('uc_rbkmoney_eshopId', ''),
  );
  $form['orderId'] = array(
    '#type' => 'hidden',
    '#value' => $order->order_id,
  );
  $form['serviceName'] = array(
    '#type' => 'hidden',
    '#value' => $desc,
  );
  $form['recipientAmount'] = array(
    '#type' => 'hidden',
    '#value' => $order->order_total,
  );
  $form['recipientCurrency'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('uc_rbkmoney_recipientCurrency', 'RUR'),
  );

    $recurring = variable_get('uc_rbkmoney_recurring', 'false');
  if ($recurring == 'true') {
    $form['recurring'] = array(
      '#type' => 'hidden',
      '#value' => $recurring,
    );
  }

  $version = variable_get('uc_rbkmoney_version', 1);
  if ($version == 2) {
    $form['version'] = array(
      '#type' => 'hidden',
      '#value' => $version,
    );
  }

  $direct = variable_get('uc_rbkmoney_direct', 'false');
  if ($direct == 'true') {
    $form['direct'] = array(
      '#type' => 'hidden',
      '#value' => $direct,
    );
  }

  $language = variable_get('uc_rbkmoney_language', 'ru');
  if ($language != 'ru') {
    $form['language'] = array(
      '#type' => 'hidden',
      '#value' => $language,
    );
  }

  $pref = variable_get('uc_rbkmoney_preference', 'all');
  if ($pref != 'all') {
    $form['preference'] = array(
      '#type' => 'hidden',
      '#value' => $pref,
    );
  }

  $form['user_email'] = array(
    '#type' => 'hidden',
    '#value' => $order->primary_email,
  );

  global $base_url;
  $form['successUrl'] = array(
    '#type' => 'hidden',
    '#value' => $base_url . '/uc_rbkmoney/success',
  );
  $form['failUrl'] = array(
    '#type' => 'hidden',
    '#value' => $base_url . '/uc_rbkmoney/fail',
  );
  $form['#action'] = variable_get('uc_rbkmoney_actionURL', 'https://rbkmoney.ru/acceptpurchase.aspx');
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Place your order'),
  );
  return $form;
}

/**
 * Callback for RBK Money system response.
 */
function uc_rbkmoney_done_payment() {

  // Check for allowed IP
  if (variable_get('uc_rbkmoney_ip', 'off') == 'on') {
    $ip_list = variable_get('uc_rbkmoney_allowed_ip', '89.111.188.128, 46.38.182.208, 46.38.182.209, 46.38.182.210');
    $allowed_ip = explode(',', $ip_list);
    //$allowed_ip = array('89.111.188.128', '46.38.182.208', '46.38.182.209', '46.38.182.210');
    $valid_ip = in_array($_SERVER['REMOTE_ADDR'], $allowed_ip);
    if (!$valid_ip) {
      watchdog("uc_rbkmoney", "Possible fraud. Error with remote IP address = " . $_SERVER['REMOTE_ADDR'] . ". The remote address of the script posting to this notify script does not match a valid RBK Money ip address");
      exit();
    }
  }

  drupal_set_header('Content-type: text/html; charset=iso-8859-1');

  if (variable_get('uc_rbkmoney_log', 'on') == 'on') {
    $log = var_export($_POST, TRUE);
    watchdog('uc_rbkmoney', '<pre>%log</pre>', array('%log' => $log));
  }

  $response['orderId'] = $_POST['orderId'];
  $response['serviceName'] = $_POST['serviceName'];
  $response['eshopAccount'] = $_POST['eshopAccount'];
  $response['paymentStatus'] = $_POST['paymentStatus'];
  $response['userName'] = $_POST['userName'];
  $response['userEmail'] = $_POST['userEmail'];
  $response['paymentData'] = $_POST['paymentData'];
  $response['hash'] = $_POST['hash'];

  if (!empty($response['hash'])) {

    $order = uc_order_load($response['orderId']);

    // Hash checking. Values of eshopId, recipientCurrency taken from the settings; recipientAmount - from order, to prevent form substitution in browser.
    $string = variable_get('uc_rbkmoney_eshopId', '') . '::' . $response['orderId'] . '::' . $response['serviceName'] . '::' . $response['eshopAccount'] . '::' . number_format($order->order_total, 2, '.', '') . '::' . variable_get('uc_rbkmoney_recipientCurrency', 'RUR') . '::' . $response['paymentStatus'] . '::' . $response['userName'] . '::' . $response['userEmail'] . '::' . $response['paymentData'] . '::' . variable_get('uc_rbkmoney_secretKey', '');
    $crc = md5($string);

    if ($response['hash'] == $crc) {
      switch ($response['paymentStatus']) {
        case STATUS_PROCESS :
          uc_order_update_status($response['orderId'], 'processing');
          uc_order_comment_save($response['orderId'], $order->uid, t('RBK Money: processing'), $type = 'admin', $status = 1, $notify = FALSE);
          break;
        case STATUS_SUCCESS :
          uc_payment_enter($response['orderId'], 'RBK Money', $order->order_total, $order->uid, NULL, NULL);
          uc_cart_complete_sale($order);
          uc_order_comment_save($response['orderId'], $order->uid, t('RBK Money: payment successful'), $type = 'admin', $status = 1, $notify = FALSE);
          break;
      }
    } elseif ($response['hash'] !== $crc) {
      uc_order_update_status($response['orderId'], 'canceled');
      uc_order_comment_save($response['orderId'], $order->uid, t('MD5 checksum fail, possible fraud. Order canceled'), $type = 'admin', $status = 1, $notify = FALSE);
      watchdog('uc_rbkmoney', 'MD5 checksum fail, possible fraud. Order canceled');
    }
  }
}

/**
 * Callback redirect from RBK Money site.
 */
function uc_rbkmoney_payment_end($arg) {
  switch ($arg) {
    case "success" :
      if (isset($_SESSION['cart_order'])) {
        $_SESSION['do_complete'] = TRUE;
        drupal_goto('cart/checkout/complete');
      }
      break;
    case "fail" :
      if (isset($_SESSION['cart_order'])) {
        unset($_SESSION['cart_order']);
        drupal_set_message(t("Your payment has been declined."));
        drupal_goto('cart');
      }
      break;
  }
  return;
}